// const eventPicks = [
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 1,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 1,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 1,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 1,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 2,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 2,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 2,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 2,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 3,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 3,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 3,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 3,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 4,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 4,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 4,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 4,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 5,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 5,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 5,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 5,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 6,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 6,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 6,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 6,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 7,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 7,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 7,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 7,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 8,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 8,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 8,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 8,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 1,
//     restaurant_picsId: 9,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 2,
//     restaurant_picsId: 9,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 3,
//     restaurant_picsId: 9,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 1,
//     userId: 4,
//     restaurant_picsId: 9,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 10,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 10,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 10,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 10,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 11,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 11,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 11,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 11,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 12,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 12,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 12,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 12,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 13,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 13,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 13,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 13,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 14,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 14,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 14,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 14,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 15,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 15,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 15,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 15,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 16,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 16,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 16,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 16,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 17,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 17,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 17,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 17,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 18,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 18,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 18,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 18,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 19,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 19,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 19,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 19,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 20,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 20,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 20,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 20,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 21,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 21,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 21,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 21,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 22,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 22,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 22,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 22,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 23,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 23,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 23,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 23,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 6,
//     restaurant_picsId: 24,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 5,
//     restaurant_picsId: 24,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 8,
//     restaurant_picsId: 24,
//     isLiked: false,
//     isSubmitted: false,
//   },
//   {
//     eventId: 2,
//     userId: 7,
//     restaurant_picsId: 24,
//     isLiked: false,
//     isSubmitted: false,
//   },
// ];
