const friends = [
  { userId: 1, friendId: 2 },
  { userId: 2, friendId: 1 },
  { userId: 1, friendId: 3 },
  { userId: 3, friendId: 1 },
  { userId: 1, friendId: 4 },
  { userId: 4, friendId: 1 },
  { userId: 1, friendId: 5 },
  { userId: 5, friendId: 5 },
  { userId: 1, friendId: 6 },
  { userId: 6, friendId: 1 },
  { userId: 6, friendId: 5 },
  { userId: 5, friendId: 6 },
  { userId: 6, friendId: 7 },
  { userId: 7, friendId: 6 },
  { userId: 6, friendId: 8 },
  { userId: 8, friendId: 6 },
  { userId: 9, friendId: 8 },
  { userId: 8, friendId: 9 },
  { userId: 5, friendId: 4 },
  { userId: 4, friendId: 5 },
  { userId: 5, friendId: 1 },
  { userId: 1, friendId: 5 },
  { userId: 7, friendId: 9 },
  { userId: 9, friendId: 7 },
];

module.exports = friends;
