const restaurant = [
  {
    name: 'Momosan Wynwood',
    street: '415 NW 26th St',
    city:'Miami',
    state: 'FL',
    zip:33127,
    phone_number:3058518450,
    email:"MomosanWynwood@gmail.com",
    password:"123",
    open_time:"5:30pm",
    close_time:"11:00pm",
    description:"Bar/Lounge, Beer, Cocktails, Corkage Fee, Delivery, Full Bar, Gender Neutral Restroom, Gluten-free Options, Non-Smoking, Takeout, Vegan, Weekend Brunch, Wheelchair Access, Wine",
    price_range:"$$",
    website_Url:"http://www.momosanwynwood.com/",
    opentableUrl:"https://www.opentable.com/r/momosan-wynwood-miami?corrid=a657feda-ff9c-4bc2-a327-0a5064468df5&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/xlarge/1/41969165.jpg"
  },
  {
    name: "Cecconis Miami Beach",
    street:"4385 Collins Ave",
    city:"Miami Beach",
    state:"FL",
    zip:33140,
    phone_number:7865077902,
    email:"Miamibeach@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"11pm",
    description:"Cecconi’s has become a critically acclaimed dining destination featuring simply prepared Venetian inspired food and offers an elegant and relaxed dining experience to enjoy the cuisine of celebrated executive chef Sergio Sigala.",
    price_range:"$$$",
    website_Url:"https://www.cecconismiamibeach.com/?utm_source=google&utm_medium=organic&utm_campaign=googlemybusiness",
    opentableUrl:"https://www.opentable.com/r/cecconis-miami-beach-miami-beach?corrid=a657feda-ff9c-4bc2-a327-0a5064468df5&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://www.cecconismiamibeach.com/system/files/112017/5a1c8361ebeeb50173000002/full_bleed/Copyright_Soho_House_Beach_House_Miami_201710_DB_LR_025.jpg?1511818541"
  },
  {
    name: 'STK Steakhouse',
    street:"2305 Collins Ave",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:3056046988,
    email:"stksteakhouse.com",
    password:"123",
    open_time:"3pm",
    close_time:"12am",
    description:"STK Miami is located in the heart of Miami Beach, bringing the pulse of New York to the rhythm of South Beach.",
    price_range:"$$$",
    website_Url:"https://stksteakhouse.com/venues/south-beach/",
    opentableUrl:"https://www.opentable.com/r/stk-miami-beach-miami?corrid=a657feda-ff9c-4bc2-a327-0a5064468df5&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/xlarge/1/29541931.jpg"
  },
  {
    name: "Blue Ribbon Sushi Bar & Grill - South Beach",
    street:"The Plymouth Hotel, 336 21st St",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:3058000404,
    email:"Blueribbon@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Blue Ribbon Sushi Bar & Grill is nestled in the historic and newly restored Plymouth Hotel in the burgeoning Mid-Beach district, just 3 blocks from the beach. The restaurant includes a spacious cocktail bar, sushi bar, indoor dining rooms and an outdoor patio area by the poolside.",
    price_range:"$$",
    website_Url:"https://www.eatblueribbonmiami.com/",
    opentableUrl:"https://www.opentable.com/r/blue-ribbon-sushi-bar-and-grill-south-beach-miami?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://popmenucloud.com/cdn-cgi/image/width%3D1920%2Cheight%3D1920%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/djfiehqv/aea41e4b-4609-4c08-b8d7-6558b01acc63.jpeg"
  },
  {
    name: "Orange Blossom",
    street:"2000 Collins Ave #7",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:7867417128,
    email:"Orangeblossom@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Orange Blossom pays tribute to this legacy by creating a warm and inviting social space, a neighborhood gathering spot, where our market-to-table, New American cuisine is highlighted by our specialty craft cocktails. ",
    price_range:"$$",
    website_Url:"orangeblossommiami.com",
    opentableUrl:"https://www.opentable.com/orange-blossom?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/3/41523500.jpg"
  },
  {
    name: "The Social Club - Surfcomber South Beach",
    street:"1717 Collins Ave",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:3056041800,
    email:"Socialclub@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Your Social Club dining experience includes locally loved, American-inspired, fare in the form of social plates, large plates and dessert—all with a creative twist.",
    price_range:"$$",
    website_Url:"ocialclubatsurfcomber.com",
    opentableUrl:"https://www.opentable.com/the-social-club-surfcomber-south-beach?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/xlarge/2/46964116.jpg"
  },
  {
    name: "Layla",
    street:" 2216 Park Ave",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:8444631215,
    email:"Laylamiami@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"A refreshingly inviting, communal and upbeat restaurant set on the serene Collins Canal.",
    price_range:"$$$",
    website_Url:"https://www.kayakmb.com/restaurant/layla",
    opentableUrl:"https://www.opentable.com/r/layla-miami-beach1?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/2/41917523.jpg"
  },
  {
    name: "Meet Dalia",
    street:"640 Ocean Dr",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:3056046988,
    email:"Meetdalia@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Simple and elegant, Meet Dalia will apply a modern approach to classic plates, delighting guests with laidback sophistication; where city meets ocean. ",
    price_range:"$$$",
    website_Url:"https://meetdaliamiami.com/",
    opentableUrl:"https://www.opentable.com/r/dalia-miami-beach?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/3/42788913.jpg"
  },
  {
    name: "Sola Miami Beach",
    street:"1000 Collins Ave",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:3057093955,
    email:"Solamiami@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Sola is very Famous for Brunch and Dinner any day of the week. They offer you an exhaustive New American Cuisine with a Latin Twist.",
    price_range:"$$$",
    website_Url:"https://www.solamiami.com/",
    opentableUrl:"https://www.opentable.com/r/sola-miami-beach?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/3/28779474.jpg"
  },
  {
    name: "Fiola Miami",
    street:"1500 San Ignacio Ave",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:3059122639,
    email:"Fiolamiami@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Fiola Miami brings the cuisine and culture of Italy to Coral Gables, 'The City Beautiful'. Recognized as one of the best fine-dining Italian restaurants in South Florida, Fiola Miami is Fabio Trabocchi's first restaurant venture outside of Washington D.C. ",
    price_range:"$$$$",
    website_Url:"fiolamiami.com",
    opentableUrl:"https://www.opentable.com/r/fiola-miami-coral-gables?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/3/48047014.jpg"
  },
  {
    name: "Limonada Bar + Brunch",
    street:"825 Washington Ave",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:3055264592,
    email:"Limonadabar@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Limonada Bar + Brunch is the ultimate restaurant and sports bar experience to have Fun in Miami Beach.",
    price_range:"$$",
    website_Url:"limonadasouthbeach.com",
    opentableUrl:"https://www.opentable.com/r/limonada-bar-and-brunch-miami-beach?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/2/41857461.jpg"
  },
  {
    name: "Azabu Miami Beach",
    street:"161 Ocean Dr,",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:7862760520,
    email:"Azabu@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Reservations for the Omakase sushi counter, The Den, are taken by Opentable 'the Den' account, phone or Azabu Miami Beach website.",
    price_range:"$$$",
    website_Url:"azabuglobal.com",
    opentableUrl:"https://www.opentable.com/r/azabu-miami-beach?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/2/25283315.png"
  },
  {
    name: "Como Como - Marisqueria",
    street:"919 Washington Ave",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:3054238004,
    email:"ComoComo@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Voted best seafood restaurant in Miami by Miami New Times, Best of Miami 2021.",
    price_range:"$$$$",
    website_Url:"comocomomiami.com",
    opentableUrl:"https://www.opentable.com/r/como-como-marisqueria-miami-beach?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/2/42010733.jpg"
  },
  {
    name: "Petralunga",
    street:"7601 E Treasure Dr Unit Cu-21",
    city:"North Bay Village",
    state:"FL",
    zip: 33141,
    phone_number:3053978676,
    email:"Petralunga@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"Petralunga is an Italian brand specialized in Contemporary Pizza Gourmet, Mediterranean cuisine and Cocktail. Founded from Italian's Restaurateurs, finally this concept landed in Miami. ",
    price_range:"$$$",
    website_Url:"https://petralunga.com/",
    opentableUrl:"https://www.opentable.com/r/petralunga-north-bay-village?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/wide-huge/1/41849268.jpg"
  },
  {
    name: "Lolo's Surf Cantina",
    street:"161 Ocean Dr",
    city:"Miami Beach",
    state:"FL",
    zip:33139,
    phone_number:7862760535,
    email:"Lolosurf@gmail.com",
    password:"123",
    open_time:"11am",
    close_time:"12am",
    description:"For those who want to escape life’s daily woes and return to a place where rolling waves meet crystal clear skies, there is Lolo's Surf Cantina.",
    price_range:"$$$",
    website_Url:"https://loloscantina.com/",
    opentableUrl:"https://www.opentable.com/r/lolos-surf-cantina-miami-beach?corrid=6b1adac9-610f-4900-98d3-580155e8d0f2&avt=eyJ2IjoyLCJtIjoxLCJwIjowLCJzIjowLCJuIjowfQ&p=2&sd=2022-05-05T19%3A00%3A00",
    profile_picUrl:"https://resizer.otstatic.com/v2/photos/xlarge/1/25197462.jpg"
  },
]
module.exports = restaurant

// {
//   userId: 1,
//   orderId: 1,
//   productId: 11,
//   quantity: 3,
//   uniPrice: 299,
//   totalPrice: 897,
// },
