const users = [
  {
    // id: 1,
    first_name: 'Yuzuru',
    last_name: 'Hanyu',
    email: 'yuzuru@gmail.com',
    password: '11111',
    password_confirm: '11111',
    preferred_city: 'Chicago',
    phone_number: '3120001111',
    isAdmin: true,
    prof_picUrl:
      'https://ocasia.org/media/cache/33/a9/33a980b5e46e266dee1c089f9d9955c9.jpg',
  },
  {
    // id: 2,
    first_name: 'Roseanne',
    last_name: 'Park',
    email: 'rose@gmail.com',
    password: '22222',
    preferred_city: 'New York',
    phone_number: '9170001234',
    isAdmin: false,
    prof_picUrl:
      'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fwp-content%2Fblogs.dir%2F6%2Ffiles%2F2021%2F09%2Fblackpink-rose-attending-met-gala-saint-laurent-nyc-0.jpg',
  },
  {
    // id: 3,
    first_name: 'Yoona',
    last_name: 'Im',
    email: 'yoona@gmail.com',
    password: '12345',
    preferred_city: 'New York',
    phone_number: '9171231234',
    isAdmin: true,
    prof_picUrl:
      'https://imageio.forbes.com/specials-images/imageserve/603a6fce0e0872311a50f147/Yoona-played-an-outspoken-intern-reporter-in-the-drama--Hush--/960x0.jpg?fit=bounds&format=jpg&width=960',
  },
  {
    // id: 4,
    first_name: 'Jennie',
    last_name: 'Kim',
    email: 'jennie@gmail.com',
    password: '54321',
    preferred_city: 'Los Angeles',
    phone_number: '9170023111',
    isAdmin: false,
    prof_picUrl:
      'https://yaay.today/__export/1610310287244/sites/yaay/img/2021/01/10/jeeniekim-grid.jpg_2062789929.jpg',
  },
  {
    // id: 5,
    first_name: 'Eileen',
    last_name: 'Gu',
    email: 'eileen@gmail.com',
    password: '121212',
    preferred_city: 'New York',
    phone_number: '9170908765',
    isAdmin: false,
    prof_picUrl:
      'https://imageio.forbes.com/specials-images/imageserve/6202cc9ffef21c71b15f068a/Eileen-Gu-of-Team-China/960x0.jpg',
  },
  {
    // id: 6,
    first_name: 'Nayeon',
    last_name: 'Im',
    email: 'nayeon@gmail.com',
    password: '123123',
    preferred_city: 'Miami',
    phone_number: '7860908765',
    isAdmin: false,
    prof_picUrl:
      'https://channel-korea.com/wp-content/uploads/2021/05/nayeon-quoracom.jpeg',
  },
  {
    // id: 7,
    first_name: 'Jackson',
    last_name: 'Wang',
    email: 'jackson@gmail.com',
    password: '321123',
    preferred_city: 'Miami',
    phone_number: '7861118765',
    isAdmin: false,
    prof_picUrl:
      'https://www.bollywoodhungama.com/wp-content/uploads/2020/05/GOT7s-Jackson-Wang-would-love-to-learn-Indian-dialect.jpg',
  },
  {
    // id: 8,
    first_name: 'Lisa',
    last_name: 'Manoban',
    email: 'lisa@gmail.com',
    password: '123321',
    preferred_city: 'Los Angeles',
    phone_number: '7861118765',
    isAdmin: false,
    prof_picUrl: 'https://otakukart.com/wp-content/uploads/2021/07/lisa.jpg',
  },
  {
    // id: 9,
    first_name: 'Jisoo',
    last_name: 'Kim',
    email: 'jisoo@gmail.com',
    password: '321123',
    preferred_city: 'Chicago',
    phone_number: '3121111234',
    isAdmin: false,
    prof_picUrl:
      'https://images.news18.com/ibnlive/uploads/2021/08/1627891727_jisoo.jpg',
  },
]
module.exports = users
